name: Bug Report
description: File a bug report.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Please describe the bug.
      placeholder: Description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: What are the steps to reproduce?
      description: Please describe the steps to reproduce the bug.
      placeholder: |
        Step 1: ...
        Step 2: ...
        Step 3: ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: Please describe the behavior you expect.
      placeholder: I expect that...
    validations:
      required: true
  - type: textarea
    id: error-thrown
    attributes:
      label: What is the error thrown?
      description: Please provide the exact error thrown.
      placeholder: This is the unexpected behaviour...
    validations:
      required: true
  - type: textarea
    id: source-path
    attributes:
      label: What is the exact source path?
      description: Please provide the exact source path.
      placeholder: Given method or property failing..
    validations:
      required: true
